# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sign_interpreter.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'sign_interpreter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sign_interpreter.proto\x12\x0bopensign.ai\"+\n\x08Landmark\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"M\n\rHandLandmarks\x12\x12\n\nconfidence\x18\x01 \x01(\x02\x12(\n\tlandmarks\x18\x02 \x03(\x0b\x32\x15.opensign.ai.Landmark\"}\n\tPoseFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12-\n\tleft_hand\x18\x02 \x01(\x0b\x32\x1a.opensign.ai.HandLandmarks\x12.\n\nright_hand\x18\x03 \x01(\x0b\x32\x1a.opensign.ai.HandLandmarks\"A\n\x0eInterpretation\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05gloss\x18\x03 \x01(\t2S\n\x0fSignInterpreter\x12@\n\tInterpret\x12\x16.opensign.ai.PoseFrame\x1a\x1b.opensign.ai.Interpretationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sign_interpreter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANDMARK']._serialized_start=39
  _globals['_LANDMARK']._serialized_end=82
  _globals['_HANDLANDMARKS']._serialized_start=84
  _globals['_HANDLANDMARKS']._serialized_end=161
  _globals['_POSEFRAME']._serialized_start=163
  _globals['_POSEFRAME']._serialized_end=288
  _globals['_INTERPRETATION']._serialized_start=290
  _globals['_INTERPRETATION']._serialized_end=355
  _globals['_SIGNINTERPRETER']._serialized_start=357
  _globals['_SIGNINTERPRETER']._serialized_end=440
# @@protoc_insertion_point(module_scope)
