# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sign_interpreter_pb2 as sign__interpreter__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sign_interpreter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignInterpreterStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Interpret = channel.unary_unary(
                '/opensign.ai.SignInterpreter/Interpret',
                request_serializer=sign__interpreter__pb2.PoseFrame.SerializeToString,
                response_deserializer=sign__interpreter__pb2.Interpretation.FromString,
                _registered_method=True)


class SignInterpreterServicer:
    """Missing associated documentation comment in .proto file."""

    def Interpret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignInterpreterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Interpret': grpc.unary_unary_rpc_method_handler(
                    servicer.Interpret,
                    request_deserializer=sign__interpreter__pb2.PoseFrame.FromString,
                    response_serializer=sign__interpreter__pb2.Interpretation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opensign.ai.SignInterpreter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('opensign.ai.SignInterpreter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SignInterpreter:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Interpret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensign.ai.SignInterpreter/Interpret',
            sign__interpreter__pb2.PoseFrame.SerializeToString,
            sign__interpreter__pb2.Interpretation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
